### PR TITLE
Convert from fuse-box to webpack.

### PR DESCRIPTION
**Pull request by dessalines**
Okay I finally got webpack working! 

Some notes:

- Works with the latest inferno!
- I had to remove the tests, as they were tied to fuse. I'm not exactly sure the right way to do inferno testing.
- Uses nodemon to do hot-reloading, which rebuilds both the server and client webpacks.

### CODE REVIEW

**Comment by 0x241F31** [comment]
May we use webpack dev server instead of nodemon?

**Comment by dessalines** [comment]
I couldn't get that to work, since it needs to load both the webpack server and client, but you could try.

**Comment by 0x241F31** [comment]
There is way to export both webpack configurations. I will try to checkout it this week

**Comment by dessalines** [comment]
bump

**Pull request closed without merging**
